### ISSUE TITLE
Bug: possible to see how other players voted

### ISSUE THREAD

**Issue by astajas-zeni** [ZenitechSoftware/planning-chess#136]
Update waiter move message payload to not contain actual player move details. Only indication that player made the move.

In console it is possible to see how other players voted even though my vote is not finished yet
![Screenshot_8](https://user-images.githubusercontent.com/114477385/193276351-4f19572c-8a57-46db-ad78-6661af813eec.png)

**Comment by KristinaKrev** [comment]
Tested on local environment.
In console it is possible to see how other players voted even though game is not finished yet.

**Comment by jvalatkevicius** [comment]
> Tested on local environment. In console it is possible to see how other players voted even though game is not finished yet.

We did not remove the logs in the local environment for debugging reasons. After deploying to production environment logs should not be visible anymore.
